package com.example.promotion.enums;

public enum ValidationErrorType {
    EXPIRED,
    INVALID_PAYMENT_MODE,
    INVALID_VEHICLE_TYPE,
    MINIMUM_FARE_NOT_MET,
    INVALID_TIME_WINDOW,
    INVALID_AREA,
    USAGE_LIMIT_EXCEEDED,
    WEATHER_CONDITION_MISMATCH,
    INVALID_RIDE_TYPE,
    INSUFFICIENT_CONSECUTIVE_RIDES,
    INVALID_DAY
}
